import {Face, PlayingCard, PlayingCardType, Suit} from "./playing-card";

export const JOKER: PlayingCard = {identifier: "JOK", type: PlayingCardType.JOKER}
export const EXCUSE: PlayingCard = {identifier: "EXC", type: PlayingCardType.EXCUSE}

export const DIAMOND_1: PlayingCard = {identifier: "1D", value: 1, suit: Suit.DIAMONDS, type: PlayingCardType.CLASSIC}
export const DIAMOND_2: PlayingCard = {identifier: "2D", value: 2, suit: Suit.DIAMONDS, type: PlayingCardType.CLASSIC}
export const DIAMOND_3: PlayingCard = {identifier: "3D", value: 3, suit: Suit.DIAMONDS, type: PlayingCardType.CLASSIC}
export const DIAMOND_4: PlayingCard = {identifier: "4D", value: 4, suit: Suit.DIAMONDS, type: PlayingCardType.CLASSIC}
export const DIAMOND_5: PlayingCard = {identifier: "5D", value: 5, suit: Suit.DIAMONDS, type: PlayingCardType.CLASSIC}
export const DIAMOND_6: PlayingCard = {identifier: "6D", value: 6, suit: Suit.DIAMONDS, type: PlayingCardType.CLASSIC}
export const DIAMOND_7: PlayingCard = {identifier: "7D", value: 7, suit: Suit.DIAMONDS, type: PlayingCardType.CLASSIC}
export const DIAMOND_8: PlayingCard = {identifier: "8D", value: 8, suit: Suit.DIAMONDS, type: PlayingCardType.CLASSIC}
export const DIAMOND_9: PlayingCard = {identifier: "9D", value: 9, suit: Suit.DIAMONDS, type: PlayingCardType.CLASSIC}
export const DIAMOND_10: PlayingCard = {identifier: "0D", value: 10, suit: Suit.DIAMONDS, type: PlayingCardType.CLASSIC}
export const DIAMOND_J: PlayingCard = {identifier: "JD", suit: Suit.DIAMONDS, face: Face.J, type: PlayingCardType.FACE}
export const DIAMOND_C: PlayingCard = {identifier: "CD", suit: Suit.DIAMONDS, face: Face.C, type: PlayingCardType.FACE}
export const DIAMOND_Q: PlayingCard = {identifier: "QD", suit: Suit.DIAMONDS, face: Face.Q, type: PlayingCardType.FACE}
export const DIAMOND_K: PlayingCard = {identifier: "KD", suit: Suit.DIAMONDS, face: Face.K, type: PlayingCardType.FACE}

export const CLUB_1: PlayingCard = {identifier: "1C", value: 1, suit: Suit.CLUBS, type: PlayingCardType.CLASSIC}
export const CLUB_2: PlayingCard = {identifier: "2C", value: 2, suit: Suit.CLUBS, type: PlayingCardType.CLASSIC}
export const CLUB_3: PlayingCard = {identifier: "3C", value: 3, suit: Suit.CLUBS, type: PlayingCardType.CLASSIC}
export const CLUB_4: PlayingCard = {identifier: "4C", value: 4, suit: Suit.CLUBS, type: PlayingCardType.CLASSIC}
export const CLUB_5: PlayingCard = {identifier: "5C", value: 5, suit: Suit.CLUBS, type: PlayingCardType.CLASSIC}
export const CLUB_6: PlayingCard = {identifier: "6C", value: 6, suit: Suit.CLUBS, type: PlayingCardType.CLASSIC}
export const CLUB_7: PlayingCard = {identifier: "7C", value: 7, suit: Suit.CLUBS, type: PlayingCardType.CLASSIC}
export const CLUB_8: PlayingCard = {identifier: "8C", value: 8, suit: Suit.CLUBS, type: PlayingCardType.CLASSIC}
export const CLUB_9: PlayingCard = {identifier: "9C", value: 9, suit: Suit.CLUBS, type: PlayingCardType.CLASSIC}
export const CLUB_10: PlayingCard = {identifier: "0C", value: 10, suit: Suit.CLUBS, type: PlayingCardType.CLASSIC}
export const CLUB_J: PlayingCard = {identifier: "JC", suit: Suit.CLUBS, face: Face.J, type: PlayingCardType.FACE}
export const CLUB_C: PlayingCard = {identifier: "CC", suit: Suit.CLUBS, face: Face.C, type: PlayingCardType.FACE}
export const CLUB_Q: PlayingCard = {identifier: "QC", suit: Suit.CLUBS, face: Face.Q, type: PlayingCardType.FACE}
export const CLUB_K: PlayingCard = {identifier: "KC", suit: Suit.CLUBS, face: Face.K, type: PlayingCardType.FACE}

export const HEART_1: PlayingCard = {identifier: "1H", value: 1, suit: Suit.HEARTS, type: PlayingCardType.CLASSIC}
export const HEART_2: PlayingCard = {identifier: "2H", value: 2, suit: Suit.HEARTS, type: PlayingCardType.CLASSIC}
export const HEART_3: PlayingCard = {identifier: "3H", value: 3, suit: Suit.HEARTS, type: PlayingCardType.CLASSIC}
export const HEART_4: PlayingCard = {identifier: "4H", value: 4, suit: Suit.HEARTS, type: PlayingCardType.CLASSIC}
export const HEART_5: PlayingCard = {identifier: "5H", value: 5, suit: Suit.HEARTS, type: PlayingCardType.CLASSIC}
export const HEART_6: PlayingCard = {identifier: "6H", value: 6, suit: Suit.HEARTS, type: PlayingCardType.CLASSIC}
export const HEART_7: PlayingCard = {identifier: "7H", value: 7, suit: Suit.HEARTS, type: PlayingCardType.CLASSIC}
export const HEART_8: PlayingCard = {identifier: "8H", value: 8, suit: Suit.HEARTS, type: PlayingCardType.CLASSIC}
export const HEART_9: PlayingCard = {identifier: "9H", value: 9, suit: Suit.HEARTS, type: PlayingCardType.CLASSIC}
export const HEART_10: PlayingCard = {identifier: "0H", value: 10, suit: Suit.HEARTS, type: PlayingCardType.CLASSIC}
export const HEART_J: PlayingCard = {identifier: "JH", suit: Suit.HEARTS, face: Face.J, type: PlayingCardType.FACE}
export const HEART_C: PlayingCard = {identifier: "CH", suit: Suit.HEARTS, face: Face.C, type: PlayingCardType.FACE}
export const HEART_Q: PlayingCard = {identifier: "QH", suit: Suit.HEARTS, face: Face.Q, type: PlayingCardType.FACE}
export const HEART_K: PlayingCard = {identifier: "KH", suit: Suit.HEARTS, face: Face.K, type: PlayingCardType.FACE}

export const SPADE_1: PlayingCard = {identifier: "1S", value: 1, suit: Suit.SPADES, type: PlayingCardType.CLASSIC}
export const SPADE_2: PlayingCard = {identifier: "2S", value: 2, suit: Suit.SPADES, type: PlayingCardType.CLASSIC}
export const SPADE_3: PlayingCard = {identifier: "3S", value: 3, suit: Suit.SPADES, type: PlayingCardType.CLASSIC}
export const SPADE_4: PlayingCard = {identifier: "4S", value: 4, suit: Suit.SPADES, type: PlayingCardType.CLASSIC}
export const SPADE_5: PlayingCard = {identifier: "5S", value: 5, suit: Suit.SPADES, type: PlayingCardType.CLASSIC}
export const SPADE_6: PlayingCard = {identifier: "6S", value: 6, suit: Suit.SPADES, type: PlayingCardType.CLASSIC}
export const SPADE_7: PlayingCard = {identifier: "7S", value: 7, suit: Suit.SPADES, type: PlayingCardType.CLASSIC}
export const SPADE_8: PlayingCard = {identifier: "8S", value: 8, suit: Suit.SPADES, type: PlayingCardType.CLASSIC}
export const SPADE_9: PlayingCard = {identifier: "9S", value: 9, suit: Suit.SPADES, type: PlayingCardType.CLASSIC}
export const SPADE_10: PlayingCard = {identifier: "0S", value: 10, suit: Suit.SPADES, type: PlayingCardType.CLASSIC}
export const SPADE_J: PlayingCard = {identifier: "JS", suit: Suit.SPADES, face: Face.J, type: PlayingCardType.FACE}
export const SPADE_C: PlayingCard = {identifier: "CS", suit: Suit.SPADES, face: Face.C, type: PlayingCardType.FACE}
export const SPADE_Q: PlayingCard = {identifier: "QS", suit: Suit.SPADES, face: Face.Q, type: PlayingCardType.FACE}
export const SPADE_K: PlayingCard = {identifier: "KS", suit: Suit.SPADES, face: Face.K, type: PlayingCardType.FACE}

export const TRUMP_1: PlayingCard = {identifier: "T1", value: 1, type: PlayingCardType.TRUMP}
export const TRUMP_2: PlayingCard = {identifier: "T2", value: 2, type: PlayingCardType.TRUMP}
export const TRUMP_3: PlayingCard = {identifier: "T3", value: 3, type: PlayingCardType.TRUMP}
export const TRUMP_4: PlayingCard = {identifier: "T4", value: 4, type: PlayingCardType.TRUMP}
export const TRUMP_5: PlayingCard = {identifier: "T5", value: 5, type: PlayingCardType.TRUMP}
export const TRUMP_6: PlayingCard = {identifier: "T6", value: 6, type: PlayingCardType.TRUMP}
export const TRUMP_7: PlayingCard = {identifier: "T7", value: 7, type: PlayingCardType.TRUMP}
export const TRUMP_8: PlayingCard = {identifier: "T8", value: 8, type: PlayingCardType.TRUMP}
export const TRUMP_9: PlayingCard = {identifier: "T9", value: 9, type: PlayingCardType.TRUMP}
export const TRUMP_10: PlayingCard = {identifier: "T10", value: 10, type: PlayingCardType.TRUMP}
export const TRUMP_11: PlayingCard = {identifier: "T11", value: 11, type: PlayingCardType.TRUMP}
export const TRUMP_12: PlayingCard = {identifier: "T12", value: 12, type: PlayingCardType.TRUMP}
export const TRUMP_13: PlayingCard = {identifier: "T13", value: 13, type: PlayingCardType.TRUMP}
export const TRUMP_14: PlayingCard = {identifier: "T14", value: 14, type: PlayingCardType.TRUMP}
export const TRUMP_15: PlayingCard = {identifier: "T15", value: 15, type: PlayingCardType.TRUMP}
export const TRUMP_16: PlayingCard = {identifier: "T16", value: 16, type: PlayingCardType.TRUMP}
export const TRUMP_17: PlayingCard = {identifier: "T17", value: 17, type: PlayingCardType.TRUMP}
export const TRUMP_18: PlayingCard = {identifier: "T18", value: 18, type: PlayingCardType.TRUMP}
export const TRUMP_19: PlayingCard = {identifier: "T19", value: 19, type: PlayingCardType.TRUMP}
export const TRUMP_20: PlayingCard = {identifier: "T20", value: 20, type: PlayingCardType.TRUMP}
export const TRUMP_21: PlayingCard = {identifier: "T21", value: 21, type: PlayingCardType.TRUMP}
