import {Face, PlayingCard, PlayingCardType, Suit} from "./playing-card";

export const JOKER: PlayingCard = {type: PlayingCardType.JOKER}

export const DIAMOND_1: PlayingCard = {value: 1, suit: Suit.DIAMONDS, type: PlayingCardType.CLASSIC}
export const DIAMOND_2: PlayingCard = {value: 2, suit: Suit.DIAMONDS, type: PlayingCardType.CLASSIC}
export const DIAMOND_3: PlayingCard = {value: 3, suit: Suit.DIAMONDS, type: PlayingCardType.CLASSIC}
export const DIAMOND_4: PlayingCard = {value: 4, suit: Suit.DIAMONDS, type: PlayingCardType.CLASSIC}
export const DIAMOND_5: PlayingCard = {value: 5, suit: Suit.DIAMONDS, type: PlayingCardType.CLASSIC}
export const DIAMOND_6: PlayingCard = {value: 6, suit: Suit.DIAMONDS, type: PlayingCardType.CLASSIC}
export const DIAMOND_7: PlayingCard = {value: 7, suit: Suit.DIAMONDS, type: PlayingCardType.CLASSIC}
export const DIAMOND_8: PlayingCard = {value: 8, suit: Suit.DIAMONDS, type: PlayingCardType.CLASSIC}
export const DIAMOND_9: PlayingCard = {value: 9, suit: Suit.DIAMONDS, type: PlayingCardType.CLASSIC}
export const DIAMOND_10: PlayingCard = {value: 10, suit: Suit.DIAMONDS, type: PlayingCardType.CLASSIC}
export const DIAMOND_J: PlayingCard = {suit: Suit.DIAMONDS, face: Face.J, type: PlayingCardType.FACE}
export const DIAMOND_C: PlayingCard = {suit: Suit.DIAMONDS, face: Face.C, type: PlayingCardType.FACE}
export const DIAMOND_Q: PlayingCard = {suit: Suit.DIAMONDS, face: Face.Q, type: PlayingCardType.FACE}
export const DIAMOND_K: PlayingCard = {suit: Suit.DIAMONDS, face: Face.K, type: PlayingCardType.FACE}

export const CLUB_1: PlayingCard = {value: 1, suit: Suit.CLUBS, type: PlayingCardType.CLASSIC}
export const CLUB_2: PlayingCard = {value: 2, suit: Suit.CLUBS, type: PlayingCardType.CLASSIC}
export const CLUB_3: PlayingCard = {value: 3, suit: Suit.CLUBS, type: PlayingCardType.CLASSIC}
export const CLUB_4: PlayingCard = {value: 4, suit: Suit.CLUBS, type: PlayingCardType.CLASSIC}
export const CLUB_5: PlayingCard = {value: 5, suit: Suit.CLUBS, type: PlayingCardType.CLASSIC}
export const CLUB_6: PlayingCard = {value: 6, suit: Suit.CLUBS, type: PlayingCardType.CLASSIC}
export const CLUB_7: PlayingCard = {value: 7, suit: Suit.CLUBS, type: PlayingCardType.CLASSIC}
export const CLUB_8: PlayingCard = {value: 8, suit: Suit.CLUBS, type: PlayingCardType.CLASSIC}
export const CLUB_9: PlayingCard = {value: 9, suit: Suit.CLUBS, type: PlayingCardType.CLASSIC}
export const CLUB_10: PlayingCard = {value: 10, suit: Suit.CLUBS, type: PlayingCardType.CLASSIC}
export const CLUB_J: PlayingCard = {suit: Suit.CLUBS, face: Face.J, type: PlayingCardType.FACE}
export const CLUB_C: PlayingCard = {suit: Suit.CLUBS, face: Face.C, type: PlayingCardType.FACE}
export const CLUB_Q: PlayingCard = {suit: Suit.CLUBS, face: Face.Q, type: PlayingCardType.FACE}
export const CLUB_K: PlayingCard = {suit: Suit.CLUBS, face: Face.K, type: PlayingCardType.FACE}

export const HEART_1: PlayingCard = {value: 1, suit: Suit.HEARTS, type: PlayingCardType.CLASSIC}
export const HEART_2: PlayingCard = {value: 2, suit: Suit.HEARTS, type: PlayingCardType.CLASSIC}
export const HEART_3: PlayingCard = {value: 3, suit: Suit.HEARTS, type: PlayingCardType.CLASSIC}
export const HEART_4: PlayingCard = {value: 4, suit: Suit.HEARTS, type: PlayingCardType.CLASSIC}
export const HEART_5: PlayingCard = {value: 5, suit: Suit.HEARTS, type: PlayingCardType.CLASSIC}
export const HEART_6: PlayingCard = {value: 6, suit: Suit.HEARTS, type: PlayingCardType.CLASSIC}
export const HEART_7: PlayingCard = {value: 7, suit: Suit.HEARTS, type: PlayingCardType.CLASSIC}
export const HEART_8: PlayingCard = {value: 8, suit: Suit.HEARTS, type: PlayingCardType.CLASSIC}
export const HEART_9: PlayingCard = {value: 9, suit: Suit.HEARTS, type: PlayingCardType.CLASSIC}
export const HEART_10: PlayingCard = {value: 10, suit: Suit.HEARTS, type: PlayingCardType.CLASSIC}
export const HEART_J: PlayingCard = {suit: Suit.HEARTS, face: Face.J, type: PlayingCardType.FACE}
export const HEART_C: PlayingCard = {suit: Suit.HEARTS, face: Face.C, type: PlayingCardType.FACE}
export const HEART_Q: PlayingCard = {suit: Suit.HEARTS, face: Face.Q, type: PlayingCardType.FACE}
export const HEART_K: PlayingCard = {suit: Suit.HEARTS, face: Face.K, type: PlayingCardType.FACE}

export const SPADE_1: PlayingCard = {value: 1, suit: Suit.SPADES, type: PlayingCardType.CLASSIC}
export const SPADE_2: PlayingCard = {value: 2, suit: Suit.SPADES, type: PlayingCardType.CLASSIC}
export const SPADE_3: PlayingCard = {value: 3, suit: Suit.SPADES, type: PlayingCardType.CLASSIC}
export const SPADE_4: PlayingCard = {value: 4, suit: Suit.SPADES, type: PlayingCardType.CLASSIC}
export const SPADE_5: PlayingCard = {value: 5, suit: Suit.SPADES, type: PlayingCardType.CLASSIC}
export const SPADE_6: PlayingCard = {value: 6, suit: Suit.SPADES, type: PlayingCardType.CLASSIC}
export const SPADE_7: PlayingCard = {value: 7, suit: Suit.SPADES, type: PlayingCardType.CLASSIC}
export const SPADE_8: PlayingCard = {value: 8, suit: Suit.SPADES, type: PlayingCardType.CLASSIC}
export const SPADE_9: PlayingCard = {value: 9, suit: Suit.SPADES, type: PlayingCardType.CLASSIC}
export const SPADE_10: PlayingCard = {value: 10, suit: Suit.SPADES, type: PlayingCardType.CLASSIC}
export const SPADE_J: PlayingCard = {suit: Suit.SPADES, face: Face.J, type: PlayingCardType.FACE}
export const SPADE_C: PlayingCard = {suit: Suit.SPADES, face: Face.C, type: PlayingCardType.FACE}
export const SPADE_Q: PlayingCard = {suit: Suit.SPADES, face: Face.Q, type: PlayingCardType.FACE}
export const SPADE_K: PlayingCard = {suit: Suit.SPADES, face: Face.K, type: PlayingCardType.FACE}

export const TRUMP_1: PlayingCard = {value: 1, type: PlayingCardType.TRUMP}
export const TRUMP_2: PlayingCard = {value: 2, type: PlayingCardType.TRUMP}
export const TRUMP_3: PlayingCard = {value: 3, type: PlayingCardType.TRUMP}
export const TRUMP_4: PlayingCard = {value: 4, type: PlayingCardType.TRUMP}
export const TRUMP_5: PlayingCard = {value: 5, type: PlayingCardType.TRUMP}
export const TRUMP_6: PlayingCard = {value: 6, type: PlayingCardType.TRUMP}
export const TRUMP_7: PlayingCard = {value: 7, type: PlayingCardType.TRUMP}
export const TRUMP_8: PlayingCard = {value: 8, type: PlayingCardType.TRUMP}
export const TRUMP_9: PlayingCard = {value: 9, type: PlayingCardType.TRUMP}
export const TRUMP_10: PlayingCard = {value: 10, type: PlayingCardType.TRUMP}
export const TRUMP_11: PlayingCard = {value: 11, type: PlayingCardType.TRUMP}
export const TRUMP_12: PlayingCard = {value: 12, type: PlayingCardType.TRUMP}
export const TRUMP_13: PlayingCard = {value: 13, type: PlayingCardType.TRUMP}
export const TRUMP_14: PlayingCard = {value: 14, type: PlayingCardType.TRUMP}
export const TRUMP_15: PlayingCard = {value: 15, type: PlayingCardType.TRUMP}
export const TRUMP_16: PlayingCard = {value: 16, type: PlayingCardType.TRUMP}
export const TRUMP_17: PlayingCard = {value: 17, type: PlayingCardType.TRUMP}
export const TRUMP_18: PlayingCard = {value: 18, type: PlayingCardType.TRUMP}
export const TRUMP_19: PlayingCard = {value: 19, type: PlayingCardType.TRUMP}
export const TRUMP_20: PlayingCard = {value: 20, type: PlayingCardType.TRUMP}
export const TRUMP_21: PlayingCard = {value: 21, type: PlayingCardType.TRUMP}
